import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.scss";
import TopNavigation from "./components/TopNavigation";
import TheFooter from "./components/TheFooter";

const dmSans = DM_Sans({
  style: "normal",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export const metadata: Metadata = {
  title: "EZY Taxis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <TopNavigation />
        {children}
        <TheFooter />
      </body>
    </html>
  );
}
